import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const root = new URL('./dist/', import.meta.url).pathname.replace(/^\/(.:)/, '$1');

const head = (title, description) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${description}"><meta name="theme-color" content="#f7f3e8"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/extra.css"><script>document.documentElement.dataset.theme=localStorage.getItem('theme')||((matchMedia('(prefers-color-scheme:dark)').matches)?'dark':'light')</script><title>${title}</title></head><body><a class="skip-link" href="#main">Skip to content</a>`;

const header = `<header class="site-header"><a class="brand" href="/" aria-label="Medha Girish home"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>MEDHA GIRISH</span></a><nav class="desktop-nav" aria-label="Primary navigation"><a href="/research/">Research</a><a href="/projects/">Projects</a><a href="/experience/">Experience</a><a href="/about/">About</a><a href="/resume/">Résumé</a></nav><div class="header-actions"><button class="theme-toggle" type="button" aria-label="Switch color theme" aria-pressed="false"><span class="sun" aria-hidden="true">☼</span><span class="moon" aria-hidden="true">☾</span></button><a class="contact-link" href="/contact/">Contact</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav"><span></span><span></span></button></div><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile navigation"><a href="/research/">Research</a><a href="/projects/">Projects</a><a href="/experience/">Experience</a><a href="/about/">About</a><a href="/resume/">Résumé</a><a href="/contact/">Contact</a></nav></header>`;

const footer = `<footer class="site-footer"><div><a class="brand" href="/"><span class="brand-mark"><i></i><i></i><i></i></span><span>MEDHA GIRISH</span></a><p>Electrical engineering · communication systems · embedded AI</p></div><div><a href="https://www.linkedin.com/in/medha-girish-569566281/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/LucyStellar07" target="_blank" rel="noreferrer">GitHub</a><a href="/resume/">Résumé</a></div><span>© 2026 Medha Girish</span></footer><script src="/site.js" defer></script></body></html>`;

const page = (title, description, content) => head(title, description) + header + `<main id="main" class="page-shell">${content}</main>` + footer;
const eyebrow = text => `<p class="eyebrow"><span></span>${text}</p>`;
const pills = xs => `<div class="pill-row">${xs.map(x => `<span class="pill">${x}</span>`).join('')}</div>`;
const write = async (route, html) => { const dir = join(root, route); await mkdir(dir, { recursive: true }); await writeFile(join(dir, 'index.html'), html); };

await write('research', page('Research — Medha Girish', 'Research by Medha Girish in photonic signal recovery, adaptive communications, and learning-enabled systems.', `
  <section class="page-hero split"><div>${eyebrow('Research')}<h1>Learning systems that respect the physics.</h1><p class="lede">I study how learning can help communication systems recover, adapt, and make decisions—while staying grounded in signal models, hardware limits, and deployment constraints.</p>${pills(['Photonic systems','Signal processing','Adaptive communications','Edge intelligence'])}</div><aside class="page-hero-aside"><p>My longer-term interest is AI-native communication: intelligence woven through the physical layer, link adaptation, embedded execution, and network control.</p><div class="credential-row"><img src="/assets/iitm-logo.png" alt="Indian Institute of Technology Madras"><span class="pill">B.Tech (Honors) · EE · 2023–27</span></div></aside></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Featured publication')}<div><h2>Learning-enabled signal recovery for optical photonic ADCs</h2><p>A two-stage learning pipeline reconstructs signals from a nonlinear photonic time-stretch front end without retraining for each sampling rate or input power.</p><div class="source-actions"><a href="https://opg.optica.org/oe/fulltext.cfm?uri=oe-34-13-23722" target="_blank" rel="noreferrer">Read paper ↗</a><a href="https://pubmed.ncbi.nlm.nih.gov/42387718/" target="_blank" rel="noreferrer">PubMed ↗</a><a href="/projects/photonic-adc/">Case study</a></div></div></div><div class="metric-grid"><div class="metric"><strong>63</strong><span>dB SNDR</span></div><div class="metric"><strong>10.18</strong><span>Effective bits</span></div><div class="metric"><strong>1st</strong><span>Author</span></div><div class="metric"><strong>Top</strong><span>UG project · EE RSS</span></div></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Research map')}<div><h2>One signal path, four coupled questions</h2><p>How do we recover the waveform? How should the link adapt? What can run at the edge? How should the network coordinate? My projects approach these as one connected system.</p></div></div><div class="course-groups"><article><h3>Physical layer recovery</h3><p>Photonic ADC calibration, nonlinear distortion correction, optical impairments, modulation, and estimation.</p></article><article><h3>Adaptive signal processing</h3><p>Blind equalization, carrier-offset estimation, variable-momentum optimization, and reinforcement learning.</p></article><article><h3>Embedded intelligence</h3><p>Hardware-aware ML, boot flows, flash protection, memory and latency constraints, and dependable execution.</p></article><article><h3>Network-level control</h3><p>Radio resource management, bandits, graph coloring, safe RL, traffic simulation, and measurement.</p></article></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Current direction')}<div><h2>From post-processing to co-design</h2><p>The central opportunity is not simply to add an ML block after a receiver. It is to co-design algorithms, sensing, compute, and control so that a communication system can learn from its environment and still remain efficient, interpretable, and safe.</p><a class="button primary" href="mailto:ee23b112@smail.iitm.ac.in">Discuss research</a></div></div></section>`));

const projectCards = [
  ['physical ai','Research · Photonics','2025–26','63 dB','Photonic ADC Signal Recovery','Agnostic recovery across input power and sampling rate.','/projects/photonic-adc/'],
  ['dsp physical','DSP · Optical comms','2025','8×','Adaptive DSP Equalization','Variable-momentum CMA and joint carrier-offset correction.','/projects/adaptive-dsp/'],
  ['network ai','Inter-IIT · Networks','2025','3.99%','Adaptive Wi-Fi RRM','Bandits, graphs, event detection, and safe RL for Wi-Fi.','/projects/adaptive-wifi/'],
  ['dsp ai','RL · Optical comms','2025','~1k','RL Optical Impairment Correction','Searching hundreds of thousands of equalizer configurations.','/projects/rl-optical/'],
  ['ai','Machine learning','2025','82.5%','Dataset Condensation','Near-full performance using four percent of the data.','/projects/dataset-condensation/'],
  ['network','Measurement · Wi-Fi','2025','32','Wi-Fi Coverage Study','Indoor path-loss measurement across CFI workspaces.','/projects/wifi-coverage/'],
  ['network','Networks · Simulation','2024','Live','Network Traffic Simulator','A visual simulator for traffic flow and network behavior.','/projects/traffic-simulator/'],
  ['dsp','Communications','2024–25','5×','Communication Systems Simulations','A notebook collection spanning modulation, sampling, and noise.','/projects/communications-simulations/'],
  ['embedded ai','Embedded ML','2026','Edge','Power-grid Fault Detection','CNN inference explored under memory and latency constraints at TI.','/experience/'],
  ['product embedded','Product design','2024–25','9','PDC Prototype Portfolio','Nine interdisciplinary builds led from problem framing to demonstration.','/about/']
];

await write('projects', page('Projects — Medha Girish', 'Selected engineering and research projects by Medha Girish.', `
  <section class="page-hero">${eyebrow('Projects')}<h1>Proof in the signal, the system, and the result.</h1><p class="lede">Concise case studies across communications, signal processing, embedded systems, machine learning, and product design—with source material placed up front.</p></section>
  <section class="content-section"><div class="filter-bar" aria-label="Filter projects"><button class="active" data-filter="all">All</button><button data-filter="physical">Communications & DSP</button><button data-filter="embedded">Embedded & Edge ML</button><button data-filter="ai">AI / ML</button><button data-filter="network">Networks</button><button data-filter="product">Product Design</button></div><div class="project-grid all-projects">${projectCards.map(([cat,meta,year,metric,title,desc,href])=>`<article class="project-card" data-categories="${cat}"><div class="project-meta"><span>${meta}</span><b>${year}</b></div><div class="mini-metric">${metric}</div><h3>${title}</h3><p>${desc}</p><a href="${href}">Open project <span>↗</span></a></article>`).join('')}</div></section>`));

await write('experience', page('Experience & Education — Medha Girish', 'Experience, education, coursework, honors, and technical skills of Medha Girish.', `
  <section class="page-hero split"><div>${eyebrow('Experience & education')}<h1>Ideas carried all the way to implementation.</h1><p class="lede">Research, embedded software, teaching, technical leadership, and a foundation across signals, systems, computation, and mathematics.</p></div><aside class="page-hero-aside"><div class="credential-row"><img src="/assets/iitm-logo.png" alt="IIT Madras"><div><b>B.Tech (Honors), Electrical Engineering</b><p>IIT Madras · 2023–27 · CGPA 9.30</p></div></div></aside></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Experience')}<div><h2>Engineering under real constraints</h2></div></div><div class="timeline"><article><time>2026</time><div><h3>Embedded Software Intern · Texas Instruments</h3><p>Automotive Applications, F29x. Worked on flash-protection flows, single-flash multicore loading, and a UART secondary bootloader; explored a CNN for power-grid fault detection under latency and memory limits; fixed defects and strengthened documentation.</p>${pills(['Embedded C','Bootloaders','Multicore','Edge AI'])}</div></article><article><time>2025</time><div><h3>Inter-IIT Tech Meet · Arista Networks</h3><p>Built a client-centric Wi-Fi radio-resource-management system spanning CNN-based interference classification, multi-armed bandits, CUSUM event detection, graph coloring, and safe reinforcement learning. Presented the system at IIT Patna.</p>${pills(['ns-3','Wi-Fi','MAB','GNN','Safe RL'])}</div></article><article><time>2024</time><div><h3>Women in Semiconductor & Hardware · Texas Instruments</h3><p>Selected among 40 students from more than 2,000 applicants. Built a PWM-driven stepper-motor system with sensor feedback.</p></div></article><article><time>2025</time><div><h3>Teaching Assistant · IIT Madras</h3><p>Supported a cohort of 160 students, clarifying concepts, handling tutorials, and strengthening feedback loops between learners and instructors.</p></div></article></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Coursework')}<div><h2>A deliberately broad systems foundation</h2><p>Courses are grouped by how they inform Medha’s research—not simply by semester.</p></div></div><div class="course-groups"><article><h3>Signals & communications</h3><p>Digital Signal Processing · Communication Systems · Information Theory · Estimation Theory · RF & Optical Communications · Communication Networks</p></article><article><h3>AI & mathematics</h3><p>Foundations of Machine Learning · Advanced AI · Convex Optimization · Probability and Statistics</p></article><article><h3>Systems & computing</h3><p>Microprocessors · Computer Organization · Data Structures and Algorithms in Python · Numerical Methods in C</p></article><article><h3>Emerging systems</h3><p>Quantum Computation · Quantum Information · Data Privacy</p></article></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Honors')}<div><h2>Academic distinction</h2><div class="timeline"><article><time>2025</time><div><h3>MV Prize for Academic Excellence</h3><p>IIT Madras.</p></div></article><article><time>2023</time><div><h3>National entrance examinations</h3><p>JEE Main AIR 132 and third among girls; JEE Advanced AIR 1632; UCEED AIR 14.</p></div></article><article><time>2022</time><div><h3>SAT · 1580</h3></div></article></div></div></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Toolkit')}<div><h2>Methods and tools</h2><div class="skills-cloud">${['Python','C / C++','MATLAB','Embedded C','PyTorch','TensorFlow','Flutter','Node.js','SQL','ns-3','Wireshark','Git','Signal processing','Optimization','Reinforcement learning'].map(x=>`<span>${x}</span>`).join('')}</div></div></div></section>`));

await write('about', page('About — Medha Girish', 'About Medha Girish: engineer, product leader, communicator, dancer, and artist.', `
  <section class="page-hero split"><div>${eyebrow('About')}<h1>An engineer shaped by both rigor and making.</h1><p class="lede">I like problems that cross boundaries: theory and implementation, hardware and learning, technical depth and human need.</p></div><aside class="page-hero-aside"><img src="/assets/medha-portrait.jpg" alt="Portrait of Medha Girish" style="width:100%;aspect-ratio:1;object-fit:cover;object-position:50% 27%"></aside></section>
  <section class="content-section"><div class="section-intro">${eyebrow('How I work')}<div><h2>Model clearly. Measure honestly. Build for the constraint.</h2><p>I start by understanding the system: what is observable, what is uncertain, what the physics already tells us, and what the deployment can actually support. Learning is most useful when it complements that structure.</p></div></div><div class="course-groups"><article><h3>Systems thinking</h3><p>Connect decisions across the signal chain instead of optimizing isolated blocks.</p></article><article><h3>Evidence first</h3><p>Use measured behavior, reproducible simulation, and appropriate baselines.</p></article><article><h3>Hardware awareness</h3><p>Treat memory, power, latency, safety, and interfaces as design inputs.</p></article><article><h3>Human context</h3><p>Communicate the why, build with teams, and keep the user visible.</p></article></div></section>
  <section class="content-section about-photo"><img src="/assets/pdc-team.jpg" alt="Product Design Club team at Delta Expo 2026"><div>${eyebrow('Product leadership')}<h2>Product Design Club · CFI</h2><p>As a leader in IIT Madras’s Centre for Innovation, I worked with 50+ makers across nine interdisciplinary projects. The role involved mentoring teams, structuring project reviews, facilitating collaborations, and helping ideas move from a problem statement to a prototype. The portfolio included work associated with two patent efforts and institute-wide design challenges reaching 300+ students.</p><div class="credential-row"><img src="/assets/cfi-logo.png" alt="Centre for Innovation logo"><span class="pill">Product Design Club</span></div></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Community & communication')}<div><h2>Technology is also a public practice.</h2><div class="timeline"><article><time>InstiLite</time><div><h3>Campus product development</h3><p>Contributed to a Flutter, Node.js, and SQL platform shaped around campus use.</p></div></article><article><time>Placement Cell</time><div><h3>Student coordination</h3><p>Coordinated for a cohort of 150+ students and onboarded three companies.</p></div></article><article><time>Technovation</time><div><h3>STEM outreach</h3><p>Mentored and enabled technology learning for more than 200 girls.</p></div></article><article><time>Journalism</time><div><h3>Times of India student journalist & guest editor</h3><p>Learned to find the core of a story and communicate it to a broad audience.</p></div></article></div></div></div></section>
  <section class="content-section"><div class="section-intro">${eyebrow('Outside engineering')}<div><h2>Movement, observation, and craft</h2><p>More than ten years of Mohiniyattam have taught me discipline, expression, and attention to form. Visual art remains another way I think; that work includes consecutive art-marathon wins in 2024 and 2025.</p>${pills(['Mohiniyattam · 10+ years','Visual art','Student journalism'])}</div></div></section>`));

await write('resume', page('Résumé — Medha Girish', 'Download Medha Girish’s general, embedded systems, or signal processing résumé.', `
  <section class="page-hero">${eyebrow('Résumé')}<h1>Choose the view that fits the conversation.</h1><p class="lede">The same interdisciplinary profile, focused for general engineering, embedded software and machine learning, or signal processing and communications.</p></section>
  <section class="content-section"><div class="resume-grid"><article class="resume-card"><div class="doc-icon"><i></i><i></i><i></i><i></i></div><h2>General résumé</h2><p>Research, industry, engineering projects, leadership, and academic distinction.</p><a class="button primary" href="/assets/Medha-Girish-Resume.pdf" download>Download PDF</a></article><article class="resume-card"><div class="doc-icon"><i></i><i></i><i></i><i></i></div><h2>Embedded SW + ML</h2><p>Boot flows, hardware-aware inference, embedded C, systems work, and ML projects.</p><a class="button primary" href="/assets/Medha-Girish-Embedded-ML-CV.pdf" download>Download PDF</a></article><article class="resume-card"><div class="doc-icon"><i></i><i></i><i></i><i></i></div><h2>Signals + communications</h2><p>Photonic recovery, adaptive DSP, optical impairments, wireless networks, and simulations.</p><a class="button primary" href="/assets/Medha-Girish-Signal-Communications-CV.pdf" download>Download PDF</a></article></div></section>`));

await write('contact', page('Contact — Medha Girish', 'Contact Medha Girish for research, graduate study, and engineering opportunities.', `
  <section class="page-hero">${eyebrow('Contact')}<h1>Let’s talk about systems that learn and signals that matter.</h1><p class="lede">For research, graduate study, engineering roles, or thoughtful collaboration, email is the best place to begin.</p></section>
  <section class="contact-grid"><div><p class="eyebrow"><span></span> Email</p><a class="contact-email" href="mailto:ee23b112@smail.iitm.ac.in">ee23b112@smail.iitm.ac.in</a><a class="contact-email" href="mailto:medhabg@gmail.com">medhabg@gmail.com</a></div><div><p class="eyebrow"><span></span> Elsewhere</p><p>Research artifacts, code, and professional updates.</p><div class="contact-links"><a href="https://www.linkedin.com/in/medha-girish-569566281/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/LucyStellar07" target="_blank" rel="noreferrer">GitHub ↗</a><a href="/resume/">Résumé</a></div></div></section>`));

const figure = (asset, viewBox, label) => `<figure class="result-figure"><svg viewBox="${viewBox}" role="img" aria-label="${label}"><image href="/assets/${asset}" width="1125" height="1456"/></svg><figcaption>${label}. Selected from the linked project report.</figcaption></figure>`;

const casePage = c => page(`${c.title} — Medha Girish`, c.outcome, `
  <section class="case-hero"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/projects/">Projects</a><span>/</span><span>${c.kind}</span></nav>${eyebrow(c.kicker)}<h1>${c.title}</h1><p class="case-outcome">${c.outcome}</p><div class="source-actions">${c.sources.map((s,i)=>`<a href="${s[1]}" ${s[1].startsWith('http')?'target="_blank" rel="noreferrer"':''}>${s[0]}${s[1].startsWith('http')?' ↗':''}</a>`).join('')}</div><dl class="case-facts"><div><dt>Role</dt><dd>${c.role}</dd></div><div><dt>Year</dt><dd>${c.year}</dd></div><div><dt>Domain</dt><dd>${c.kind}</dd></div><div><dt>Read time</dt><dd>${c.read}</dd></div></dl><div class="metric-grid">${c.metrics.map(m=>`<div class="metric"><strong>${m[0]}</strong><span>${m[1]}</span></div>`).join('')}</div></section>
  <section class="case-body"><aside>${eyebrow('Case study')}<h2>${c.sidebar}</h2>${pills(c.tags)}</aside><main>${c.body}</main></section>
  <section class="related"><h2>Continue exploring</h2><div class="related-links">${c.related.map(r=>`<a href="${r[1]}"><span>Related project</span><b>${r[0]}</b></a>`).join('')}</div></section>`);

await write('projects/photonic-adc', casePage({title:'Learning-enabled signal recovery for optical photonic ADCs',kind:'Photonics · signal recovery',kicker:'First-author publication',outcome:'A power- and sampling-rate-agnostic learning pipeline that recovers high-fidelity signals from a nonlinear photonic time-stretch front end.',role:'Lead author · modelling & learning',year:'2025–26',read:'4 min',sources:[['Read the paper','https://opg.optica.org/oe/fulltext.cfm?uri=oe-34-13-23722'],['PubMed record','https://pubmed.ncbi.nlm.nih.gov/42387718/']],metrics:[['63','dB SNDR'],['10.18','ENOB'],['1st','author'],['Top','UG project · EE RSS']],sidebar:'Recover the signal without retraining for every operating point.',tags:['Photonic ADC','Deep learning','Calibration','Signal recovery'],body:`<h2>The problem</h2><p>Photonic time-stretch analog-to-digital converters can capture extremely high-bandwidth signals, but real front ends introduce nonlinear distortion through electro-optic modulation, optical filtering, dispersion, photodetection, and electronic digitization. A correction model tied to one input power or sampling rate is difficult to deploy.</p><h2>The approach</h2><p>The work separates the recovery problem into stages so the learned representation focuses on system distortion rather than memorizing one acquisition setting. Training data are built from known reference signals passed through the physical front end, and the recovered waveform is evaluated with communication-grade signal-quality metrics.</p><div class="native-chart"><span class="label top">Reported signal quality</span><span class="label bottom">increasing recovery quality</span><div class="line"><svg viewBox="0 0 500 220" preserveAspectRatio="none" aria-label="Signal quality rises through the recovery pipeline"><polyline points="0,190 95,166 190,128 285,87 380,48 500,24"/><circle cx="0" cy="190" r="7"/><circle cx="190" cy="128" r="7"/><circle cx="380" cy="48" r="7"/><circle cx="500" cy="24" r="7"/></svg></div></div><p>The final system reached a reported 63 dB signal-to-noise-and-distortion ratio and 10.18 effective bits. The architecture is designed to remain useful across sampling rates and input powers, reducing the need for repeated retraining.</p><h2>My contribution</h2><p>As first author, I worked across the research arc: system modelling, data generation, learning architecture, experimental evaluation, and the paper. The project was also selected among the top undergraduate projects at IIT Madras’s Electrical Engineering Research Scholars’ Symposium.</p><h2>Takeaway</h2><p>Learning becomes much more deployable when it encodes the invariances the physical system actually needs. The result is less a generic neural post-processor and more a calibrated component of the signal chain.</p>`,related:[['Adaptive DSP Equalization','/projects/adaptive-dsp/'],['RL Optical Impairment Correction','/projects/rl-optical/']]}));

await write('projects/adaptive-dsp', casePage({title:'Adaptive DSP equalization for optical links',kind:'Signal processing',kicker:'Adaptive algorithms',outcome:'Compared blind equalizers for polarization-mixed optical signals and developed a variable-momentum CMA path that converged up to eight times faster.',role:'Algorithm design · simulation',year:'2025',read:'4 min',sources:[['Open report','https://drive.google.com/file/d/1jBObyLL1t77WmiB6EmOhwljB9Ch1TIPl/view']],metrics:[['8×','faster convergence'],['5%','CFO error band'],['10⁶','simulated symbols'],['16','QAM']],sidebar:'Make the equalizer respond faster without giving up recovery quality.',tags:['CMA','VM-CMA','LMS','Optical comms'],body:`<h2>The problem</h2><p>Polarization-mode dispersion, phase noise, carrier-frequency offset, and additive noise can rotate and smear received constellations. Standard constant-modulus adaptation is robust but slow; higher-order modulation also complicates its single-radius assumption.</p><h2>The experiments</h2><p>I compared standard CMA with momentum, variable-momentum, second-moment, L-BFGS, and multi-modulus variants across SNR, group delay, and filter-tap settings. The strongest improvement came from adapting the momentum term as convergence approached.</p>${figure('adaptive-dsp-results.png','600 55 505 470','Convergence-symbol comparison and recovered 16-QAM constellation')}${figure('adaptive-dsp-comparison.png','70 250 510 530','EVM and convergence tradeoff for MMA and CMA')}<h2>Joint correction</h2><p>A decision-directed LMS formulation was used to estimate equalizer taps and carrier-frequency offset together, keeping the final CFO estimate within five percent of the simulated offset in the tested conditions.</p><h2>Takeaway</h2><p>There is no universally best adaptive equalizer: convergence speed, steady-state error, block processing cost, and modulation order all matter. Variable momentum offered a practical improvement because it changed the optimizer’s behavior over the course of adaptation.</p>`,related:[['Photonic ADC Signal Recovery','/projects/photonic-adc/'],['RL Optical Impairment Correction','/projects/rl-optical/']]}));

await write('projects/adaptive-wifi', casePage({title:'Client-centric adaptive Wi-Fi resource management',kind:'Networks · AI',kicker:'Inter-IIT Tech Meet',outcome:'A multi-timescale Wi-Fi controller combining measurement, bandits, graph optimization, event detection, and safe reinforcement learning.',role:'Algorithms · simulation · presentation',year:'2025',read:'5 min',sources:[['Open end-term report','https://drive.google.com/drive/folders/1ypAwZ70cLUH2xUe5M5V97-XrHcSkSnVN?usp=sharing'],['View code','https://github.com/LucyStellar07/Arista_MAB_Channel_Scanning']],metrics:[['3.99%','power-estimation gain'],['7.4%','seen-data GNN error'],['8.04%','unseen-data error'],['2','control timescales']],sidebar:'Use the client’s view to make safer network decisions.',tags:['Wi-Fi','ns-3','MAB','Graph coloring','Safe RL'],body:`<h2>The problem</h2><p>Enterprise Wi-Fi changes on several timescales. Short interference bursts need fast, local reactions; channel assignments and power policies need slower, network-wide planning. Decisions must also respect service-level objectives for voice, exams, guests, streaming, and IoT traffic.</p><h2>The system</h2><p>The design expands the access point’s view with client measurements, transport-layer quality, and fine-time measurement. A fast loop detects airtime or interference spikes and applies bounded mitigation. A slow loop builds an interference graph, ranks channels with bandit feedback, and evaluates network-wide configurations.</p>${figure('arista-graph-coloring.png','65 45 995 455','Access-point topology, interference graph, and channel coloring')}${figure('arista-rl-results.png','560 560 510 420','Learning curves for constrained reinforcement learning')}<h2>Safety before deployment</h2><p>A graph neural network predicts throughput, latency, and retry behavior for candidate states. Policies are checked against per-service constraints before being deployed; unsafe actions are rejected or rolled back. The GNN achieved errors of 7.4 percent on seen and 8.04 percent on unseen configurations in the report.</p><h2>My contribution</h2><p>I contributed to the adaptive decision pipeline, power estimation, simulation, and system integration, and presented the final work at the Inter-IIT Tech Meet hosted by IIT Patna.</p><h2>Takeaway</h2><p>Network intelligence is most useful when it is layered: fast controls for volatility, slower optimization for coordination, and explicit safeguards for real service requirements.</p>`,related:[['Wi-Fi Coverage Study','/projects/wifi-coverage/'],['Network Traffic Simulator','/projects/traffic-simulator/']]}));

await write('projects/rl-optical', casePage({title:'Reinforcement learning for optical impairment correction',kind:'RL · optical communications',kicker:'Exploratory research',outcome:'A bandit proof of concept that identified useful equalizer coefficients in roughly 1,000 rounds, motivating a scalable Q-learning formulation.',role:'Problem formulation · simulation',year:'2025',read:'4 min',sources:[['Open report','https://drive.google.com/file/d/1xQ6Jx160sgsMLP9j9n-Qn5zRYr0WThN1/view']],metrics:[['531k','discrete actions'],['~1k','UCB rounds'],['4','adaptive filters'],['72','Q-learning actions']],sidebar:'Turn equalizer search into sequential decision-making.',tags:['UCB','Q-learning','PMD','Adaptive filters'],body:`<h2>The problem</h2><p>A 2×2 polarization equalizer already contains many coupled complex coefficients. Even a heavily discretized toy version produces 3¹²—more than 531,000—possible filter combinations, which makes exhaustive evaluation impractical.</p><h2>Bandit proof of concept</h2><p>The first formulation treats coefficient sets as arms and negative CMA error as the reward. UCB balances exploration and exploitation, finding the strongest tested set in roughly 1,000 rounds for the compact case.</p>${figure('rl-optical-results.png','65 980 510 360','Received and corrected constellations in the UCB proof of concept')}<h2>Scaling with Q-learning</h2><p>Rather than selecting a complete filter independently each time, the Q-learning state represents the current coefficients and actions increment, decrement, or keep individual elements. This reduces the decision to 72 local actions and makes experience replay or a deep Q-network natural next steps.</p><h2>Takeaway</h2><p>The project clarifies where reinforcement learning helps—and where a naive action space breaks down. The useful shift is from choosing among every possible equalizer to learning how to navigate the coefficient space.</p>`,related:[['Adaptive DSP Equalization','/projects/adaptive-dsp/'],['Photonic ADC Signal Recovery','/projects/photonic-adc/']]}));

await write('projects/wifi-coverage', casePage({title:'Wi-Fi coverage in real workspaces',kind:'Wireless measurement',kicker:'Communication networks',outcome:'Measured indoor beacon strength across 32 locations and fit a compact path-loss model that captured distance and wall attenuation with R² = 0.93.',role:'Experiment · analysis · report',year:'2025',read:'3 min',sources:[['Open report & data','https://github.com/LucyStellar07/CommunicationNetworks_EE5150/tree/main/Review%20of%20Wi-fi%20Coverage%20in%20Workplaces']],metrics:[['32','measurement locations'],['~300','beacons per location'],['0.93','R² fit'],['3.03','dB per wall']],sidebar:'Measure how a real building reshapes wireless coverage.',tags:['Wi-Fi','Wireshark','Regression','Path loss'],body:`<h2>The experiment</h2><p>A monitor-mode WLAN card captured roughly 300 beacon frames at each of 32 locations inside the Centre for Innovation building. Distance from the access point, intervening walls, and RSSI were recorded across workspaces and floors.</p>${figure('wifi-coverage-report.png','80 330 1150 720','Measurement floor plan, fitted parameters, and RSSI regression')}<h2>The model</h2><p>The fitted log-distance model used a reference RSSI of −31.3 dBm, a path-loss exponent of 2.81, and a wall attenuation factor near −3.03 dB per wall. The resulting fit reached an R² of 0.93.</p><h2>Result</h2><p>Signal strength followed the expected logarithmic decay with distance, but obstacles materially shifted the readings. For the measured environment, keeping devices within roughly ten metres helped maintain stronger than −65 dBm coverage, with elevated access-point placement and line of sight offering clear benefits.</p>`,related:[['Adaptive Wi-Fi RRM','/projects/adaptive-wifi/'],['Network Traffic Simulator','/projects/traffic-simulator/']]}));

await write('projects/dataset-condensation', casePage({title:'Dataset condensation for efficient learning',kind:'Machine learning',kicker:'Data efficiency',outcome:'A compact synthetic training set preserved 82.5 percent evaluation accuracy while using only four percent of the original data.',role:'Implementation · evaluation',year:'2025',read:'3 min',sources:[['View code & report','https://github.com/LucyStellar07/Dataset_Condensation']],metrics:[['4%','training data'],['82.5%','accuracy'],['25×','data reduction'],['1','compact set']],sidebar:'Keep the information, not every example.',tags:['Data efficiency','Synthetic data','PyTorch','Evaluation'],body:`<h2>The problem</h2><p>Large training sets increase storage, iteration time, and compute cost. Dataset condensation asks whether a small set of optimized examples can carry much of the information needed to train a useful model.</p><h2>The approach</h2><p>The project generated compact synthetic samples and evaluated how well a model trained on them transferred to the full test distribution. The codebase includes the report and plotting workflow so the accuracy–compression tradeoff can be reproduced.</p><div class="native-chart"><span class="label top">Accuracy retained as data shrinks</span><span class="label bottom">synthetic set: 4% of data</span><div class="line"><svg viewBox="0 0 500 220" preserveAspectRatio="none"><polyline points="0,52 120,62 250,74 380,90 500,104"/><circle cx="500" cy="104" r="8"/></svg></div></div><h2>Result</h2><p>Using four percent of the original data, the condensed set supported 82.5 percent test accuracy. The result makes the tradeoff concrete: a 25× reduction in examples while retaining much of the decision boundary.</p><h2>Takeaway</h2><p>Efficient learning is not only about smaller models. Better-chosen data can reduce the cost of training, experimentation, and deployment pipelines.</p>`,related:[['Power-grid Fault Detection','/experience/'],['Communication Systems Simulations','/projects/communications-simulations/']]}));

await write('projects/traffic-simulator', casePage({title:'Interactive network traffic simulator',kind:'Network simulation',kicker:'Systems project',outcome:'A visual environment for experimenting with traffic flow, routing behavior, and network-level statistics.',role:'Simulation · visualization',year:'2024',read:'3 min',sources:[['View repository','https://github.com/KanakV/traffic_simulator']],metrics:[['Live','visual simulation'],['2','contributors'],['Stats','exported analysis'],['Open','source']],sidebar:'Make network behavior visible enough to reason about.',tags:['Simulation','Networks','Visualization','Python'],body:`<h2>The goal</h2><p>Queueing, route choice, and congestion are easier to understand when the network can be observed while it runs. This project turns those interactions into a visual simulator with a dashboard and statistics output.</p><h2>The build</h2><p>Developed with Kanak Varma, the repository combines simulation logic, an interface, a recorded demonstration, and a statistics report. It was structured as an inspectable experiment rather than a single fixed animation.</p><div class="native-chart"><span class="label top">Illustrative traffic load over time</span><span class="label bottom">simulation steps</span><div class="line"><svg viewBox="0 0 500 220" preserveAspectRatio="none"><polyline points="0,180 55,150 100,168 155,105 210,130 260,60 310,92 360,44 420,80 500,28"/><circle cx="155" cy="105" r="7"/><circle cx="310" cy="92" r="7"/><circle cx="500" cy="28" r="7"/></svg></div></div><h2>Takeaway</h2><p>A simulator is most useful when it connects a visual event to a measurable quantity. The project strengthened my interest in tools that let people explore system behavior, not just see a final number.</p>`,related:[['Wi-Fi Coverage Study','/projects/wifi-coverage/'],['Adaptive Wi-Fi RRM','/projects/adaptive-wifi/']]}));

await write('projects/communications-simulations', casePage({title:'Communication systems simulation notebooks',kind:'Communications',kicker:'Foundational models',outcome:'A reproducible notebook collection spanning quantization, sampling, modulation, AWGN, passband behavior, and special functions.',role:'Simulation · analysis',year:'2024–25',read:'3 min',sources:[['View notebooks','https://github.com/LucyStellar07/CommunicationSystems_Simulations']],metrics:[['5+','notebooks'],['AWGN','channel model'],['RF','passband sampling'],['DSP','quantization']],sidebar:'Build intuition by making every assumption executable.',tags:['Python','Modulation','Sampling','Noise'],body:`<h2>The collection</h2><p>The notebooks model core ideas from communication systems: quantization, passband sampling, modem behavior, additive white Gaussian noise, and Bessel-function relationships that appear in angle modulation.</p><h2>Why it matters</h2><p>Each notebook turns a derivation into an inspectable experiment. Parameters can be changed, waveforms plotted, and edge cases compared, making the material useful both for study and as a foundation for more advanced optical and wireless projects.</p><div class="native-chart"><span class="label top">Noisy channel response</span><span class="label bottom">sample index</span><div class="line"><svg viewBox="0 0 500 220" preserveAspectRatio="none"><polyline points="0,110 20,74 40,143 60,53 80,168 100,79 120,128 140,34 160,150 180,70 200,142 220,47 240,165 260,87 280,129 300,42 320,154 340,72 360,138 380,52 400,163 420,82 440,126 460,44 480,151 500,92"/></svg></div></div><h2>Takeaway</h2><p>Simulation is not a substitute for theory; it is a way to stress-test intuition. This collection became a reusable base for later adaptive-DSP and network experiments.</p>`,related:[['Adaptive DSP Equalization','/projects/adaptive-dsp/'],['Photonic ADC Signal Recovery','/projects/photonic-adc/']]}));

await write('projects/network-systems', page('Network Systems — Medha Girish', 'Network systems projects by Medha Girish.', `<section class="page-hero">${eyebrow('Project collection')}<h1>Network systems: measure, simulate, adapt.</h1><p class="lede">Three connected views of network behavior—from physical coverage, to traffic dynamics, to adaptive radio-resource decisions.</p></section><section class="content-section"><div class="project-grid">${projectCards.filter(p=>p[0].includes('network')).map(([cat,meta,year,metric,title,desc,href])=>`<article class="project-card"><div class="project-meta"><span>${meta}</span><b>${year}</b></div><div class="mini-metric">${metric}</div><h3>${title}</h3><p>${desc}</p><a href="${href}">Open project <span>↗</span></a></article>`).join('')}</div></section>`));

console.log('Generated portfolio pages.');
